// <auto-generated />
using System;
using GeoTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoTrack.Api.Migrations
{
    [DbContext(typeof(GeoTrackContext))]
    partial class GeoTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoTrack.Api.Models.PositionGps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Erreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtatVehicule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("NiveauCarburant")
                        .HasColumnType("float");

                    b.Property<string>("VehiculeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vitesse")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PositionsGps");
                });
#pragma warning restore 612, 618
        }
    }
}
